"""
ShadowMap - Module 4: Vulnerability Hints
Flags common misconfigurations — NOT exploitation, just awareness.
"""

import hashlib
import random
import string
import requests
from rich.console import Console

console = Console()

TIMEOUT = 5

# How different a finding's body length must be from the host's baseline
# ("nothing here") response to count as real, as a fraction of the
# baseline length. Raise this if you get too many false positives on
# hosts with slightly dynamic catch-all pages (timestamps, nonces, etc).
LENGTH_DIFF_THRESHOLD = 0.15

# ─── Sensitive paths to check ─────────────────────────────────────────────────

SENSITIVE_PATHS = [
    ("/.git/config",          "Git repository exposed",         "HIGH"),
    ("/.env",                 ".env file exposed",              "CRITICAL"),
    ("/.env.backup",          ".env backup exposed",            "CRITICAL"),
    ("/.env.local",           ".env.local exposed",             "CRITICAL"),
    ("/config.php",           "PHP config file exposed",        "HIGH"),
    ("/config.yml",           "YAML config exposed",            "HIGH"),
    ("/config.json",          "JSON config exposed",            "MEDIUM"),
    ("/backup.zip",           "Backup archive exposed",         "HIGH"),
    ("/backup.sql",           "SQL dump exposed",               "HIGH"),
    ("/db.sql",               "SQL dump exposed",               "HIGH"),
    ("/database.sql",         "SQL dump exposed",               "HIGH"),
    ("/phpinfo.php",          "phpinfo() exposed",              "MEDIUM"),
    ("/info.php",             "phpinfo() exposed",              "MEDIUM"),
    ("/test.php",             "Test file exposed",              "LOW"),
    ("/wp-config.php.bak",    "WordPress config backup exposed","CRITICAL"),
    ("/robots.txt",           "robots.txt (info disclosure)",   "INFO"),
    ("/sitemap.xml",          "Sitemap exposed (info)",         "INFO"),
    ("/.htaccess",            ".htaccess file exposed",         "MEDIUM"),
    ("/server-status",        "Apache server-status exposed",   "MEDIUM"),
    ("/server-info",          "Apache server-info exposed",     "MEDIUM"),
    ("/.DS_Store",            ".DS_Store exposed (macOS leak)", "LOW"),
    ("/crossdomain.xml",      "Flash crossdomain exposed",      "LOW"),
    ("/clientaccesspolicy.xml","Silverlight policy exposed",    "LOW"),
    ("/api/v1/",              "API endpoint exposed",           "INFO"),
    ("/api/v2/",              "API endpoint exposed",           "INFO"),
    ("/swagger.json",         "Swagger API docs exposed",       "MEDIUM"),
    ("/swagger-ui.html",      "Swagger UI exposed",             "MEDIUM"),
    ("/openapi.json",         "OpenAPI spec exposed",           "MEDIUM"),
    ("/graphql",              "GraphQL endpoint exposed",       "MEDIUM"),
    ("/admin",                "Admin panel exposed",            "HIGH"),
    ("/admin/",               "Admin panel exposed",            "HIGH"),
    ("/phpmyadmin/",          "phpMyAdmin exposed",             "HIGH"),
    ("/adminer.php",          "Adminer DB tool exposed",        "HIGH"),
]

SEVERITY_COLORS = {
    "CRITICAL": "bold red",
    "HIGH":     "red",
    "MEDIUM":   "yellow",
    "LOW":      "blue",
    "INFO":     "dim",
}


# Signals that a response was generated by a CDN/WAF edge node and never
# reached the origin server at all — e.g. Akamai returning its own 403 page
# for a known-scanned path like /.env, before the request hits the app.
# A finding based on one of these is "the edge has a rule for this path",
# NOT "a file exists here" — very different, and not something to report.
CDN_EDGE_BLOCK_SERVER_VALUES = [
    "akamaighost",       # Akamai's edge-generated error/block page server header
    "cloudflare-nginx",  # legacy Cloudflare block page identifier (rare)
]

CDN_EDGE_BLOCK_HEADER_SIGNATURES = [
    ("x-cache", "tcp_denied"),          # Akamai: edge denied before reaching origin
    ("cf-mitigated", "challenge"),      # Cloudflare: WAF/bot mitigation fired
    ("cf-mitigated", "block"),
    ("x-akamai-transformed", None),     # present only on Akamai-transformed edge pages (no value check needed)
]


def _is_cdn_edge_block(resp: requests.Response) -> bool:
    """
    Detect whether a response was generated by a CDN/WAF edge node rather
    than the actual origin server. Confirmed via TikTok's own traffic:
    edge-blocked responses show 'server: AkamaiGHost' + 'x-cache: TCP_DENIED'
    with none of the origin's real app headers, while genuine responses from
    the origin (even 404s) carry origin-specific headers like x-tt-trace-host
    and x-origin-response-time.
    """
    headers = {k.lower(): v for k, v in resp.headers.items()}

    server = headers.get("server", "").lower()
    if server in CDN_EDGE_BLOCK_SERVER_VALUES:
        # AkamaiGHost etc. only appears when Akamai's edge generated the
        # response itself — confirm with x-cache if present for extra safety
        x_cache = headers.get("x-cache", "").lower()
        if "denied" in x_cache or "tcp_denied" in x_cache or not x_cache:
            return True

    for header, expected_substring in CDN_EDGE_BLOCK_HEADER_SIGNATURES:
        value = headers.get(header, "")
        if value == "" and header not in headers:
            continue
        if expected_substring is None:
            return True  # header's mere presence is the signal
        if expected_substring in value.lower():
            return True

    return False


# ─── Checks ───────────────────────────────────────────────────────────────────

def _random_path() -> str:
    """Generate a random, near-certainly-nonexistent path segment."""
    junk = "".join(random.choices(string.ascii_lowercase + string.digits, k=16))
    return f"/{junk}-shadowmap-nonexistent"


def get_baseline(base_url: str) -> dict | None:
    """
    Request a random nonexistent path on this host to learn what its
    'not found' response actually looks like. Many apps (SPAs, CDNs,
    catch-all routers) return HTTP 200 with a generic page for ANY path
    instead of a real 404. Without this baseline, every sensitive path
    check below would falsely read as "exposed" on such hosts.
    """
    url = base_url.rstrip("/") + _random_path()
    try:
        resp = requests.get(
            url,
            timeout=TIMEOUT,
            verify=False,
            allow_redirects=False,
            headers={"User-Agent": "Mozilla/5.0 (ShadowMap/1.0)"}
        )
        body = resp.text or ""
        return {
            "status_code": resp.status_code,
            "length": len(body),
            "hash": hashlib.sha256(body.encode("utf-8", errors="ignore")).hexdigest(),
        }
    except Exception:
        return None


def _looks_like_baseline(resp: requests.Response, baseline: dict | None) -> bool:
    """
    Decide whether a response is just the host's generic catch-all page
    (soft-404) rather than a genuine hit on the requested path.
    """
    if not baseline:
        return False  # no baseline available — fall back to trusting status code

    if resp.status_code != baseline["status_code"]:
        return False  # different status code — worth a closer look, not a soft-404

    body = resp.text or ""
    body_hash = hashlib.sha256(body.encode("utf-8", errors="ignore")).hexdigest()

    if body_hash == baseline["hash"]:
        return True  # byte-for-byte identical to the nonexistent-path response

    # Same status, different bytes — only treat as "same page" if length is
    # also close to baseline. A real leaked file (e.g. a small .env) will
    # usually differ sharply in size from a full HTML shell.
    if baseline["length"] > 0:
        diff_ratio = abs(len(body) - baseline["length"]) / baseline["length"]
        if diff_ratio <= LENGTH_DIFF_THRESHOLD:
            return True

    return False


def check_path(base_url: str, path: str, label: str, severity: str, baseline: dict | None) -> dict | None:
    """Check if a sensitive path is accessible, filtering out soft-404s."""
    url = base_url.rstrip("/") + path
    try:
        resp = requests.get(
            url,
            timeout=TIMEOUT,
            verify=False,
            allow_redirects=False,
            headers={"User-Agent": "Mozilla/5.0 (ShadowMap/1.0)"}
        )
        # 200 = exposed, 403 = exists but forbidden (still worth noting for some)
        if resp.status_code == 200:
            if _looks_like_baseline(resp, baseline):
                return None  # matches the nonexistent-path response — soft-404, not real
            return {
                "url": url,
                "label": label,
                "severity": severity,
                "status_code": resp.status_code,
                "note": "Accessible"
            }
        elif resp.status_code == 403 and severity in ("CRITICAL", "HIGH"):
            if _is_cdn_edge_block(resp):
                return None  # edge/WAF denied the request pattern — origin was never reached
            if _looks_like_baseline(resp, baseline):
                return None
            return {
                "url": url,
                "label": label,
                "severity": "LOW",
                "status_code": resp.status_code,
                "note": "Forbidden (but exists)"
            }
    except Exception:
        pass
    return None


def check_directory_listing(base_url: str) -> dict | None:
    """Check if directory listing is enabled on root."""
    indicators = ["Index of /", "Directory listing for", "Parent Directory"]
    try:
        resp = requests.get(
            base_url,
            timeout=TIMEOUT,
            verify=False,
            headers={"User-Agent": "Mozilla/5.0 (ShadowMap/1.0)"}
        )
        for indicator in indicators:
            if indicator.lower() in resp.text.lower():
                return {
                    "url": base_url,
                    "label": "Directory listing enabled",
                    "severity": "HIGH",
                    "status_code": resp.status_code,
                    "note": f"Found indicator: '{indicator}'"
                }
    except Exception:
        pass
    return None


def check_cors(base_url: str) -> dict | None:
    """Check for overly permissive CORS policy."""
    try:
        resp = requests.get(
            base_url,
            timeout=TIMEOUT,
            verify=False,
            headers={
                "User-Agent": "Mozilla/5.0 (ShadowMap/1.0)",
                "Origin": "https://evil.com"
            }
        )
        acao = resp.headers.get("Access-Control-Allow-Origin", "")
        if acao == "*" or acao == "https://evil.com":
            return {
                "url": base_url,
                "label": "Permissive CORS policy",
                "severity": "MEDIUM",
                "status_code": resp.status_code,
                "note": f"Access-Control-Allow-Origin: {acao}"
            }
    except Exception:
        pass
    return None


# ─── Main entry ───────────────────────────────────────────────────────────────

def check_host(subdomain: str, fp_data: dict) -> list:
    """Run all vuln hint checks on a single host."""
    findings = []
    base_url = fp_data.get("base_url")
    if not base_url:
        return findings

    # Learn what this host's "nothing here" response looks like before
    # trusting any 200/403 on the sensitive paths below.
    baseline = get_baseline(base_url)

    # Sensitive paths
    for path, label, severity in SENSITIVE_PATHS:
        result = check_path(base_url, path, label, severity, baseline)
        if result:
            findings.append(result)

    # Directory listing
    dl = check_directory_listing(base_url)
    if dl:
        findings.append(dl)

    # CORS
    cors = check_cors(base_url)
    if cors:
        findings.append(cors)

    # Missing security headers (from fingerprint data)
    missing = fp_data.get("missing_security_headers", [])
    for header in missing:
        findings.append({
            "url": base_url,
            "label": f"Missing security header: {header}",
            "severity": "MEDIUM",
            "status_code": None,
            "note": "Header not present in response"
        })

    return findings


def run_vuln_hints(scan_results: dict, fp_results: dict) -> dict:
    """
    Run vulnerability hints on all hosts.
    Returns: { subdomain: [findings] }
    """
    console.print(f"\n[bold cyan][*] Checking for common misconfigurations...[/bold cyan]")

    vuln_results = {}
    for sub in scan_results:
        fp_data = fp_results.get(sub, {})
        findings = check_host(sub, fp_data)
        vuln_results[sub] = findings

        for f in findings:
            color = SEVERITY_COLORS.get(f["severity"], "white")
            if f["severity"] not in ("INFO",):
                console.print(
                    f"  [{color}][{f['severity']}][/{color}] {sub} — {f['label']} ({f['url']})"
                )

    total = sum(len(v) for v in vuln_results.values())
    console.print(f"[bold green][✓] Vuln hints complete — {total} findings flagged[/bold green]")
    return vuln_results
